# Generated by Django 2.1.7 on 2019-02-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.FloatField()),
                ('max_hp', models.FloatField()),
                ('mp', models.FloatField()),
                ('max_mp', models.FloatField()),
                ('speed', models.FloatField()),
                ('dmg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=600)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player', to='gjango_main.Player')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
