# Generated by Django 2.1.7 on 2019-02-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gjango_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Player'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='character',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='gjango_main.User'),
        ),
    ]
