# Generated by Django 2.1.7 on 2019-02-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjango_main', '0002_auto_20190222_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agility',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='dex',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='inte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='pow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='str',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='vit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='wis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='dmg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_hp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_mp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='mp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
