# Generated by Django 2.1.7 on 2019-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjango_main', '0004_auto_20190228_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clss',
            field=models.CharField(default='Error', max_length=30),
        ),
    ]
