# Generated by Django 2.1.7 on 2019-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjango_main', '0005_player_clss'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='armmor_pen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='armor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='crit_chance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='defen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='dodge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='lv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='magic_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='magic_pen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='mana_regeneration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='regeneration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_pow',
            field=models.FloatField(default=0.0),
        ),
    ]
