# Generated by Django 2.1.7 on 2019-03-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjango_main', '0008_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_points',
            field=models.FloatField(default=0.0),
        ),
    ]
